### ISSUE TITLE
using innerHtml

### ISSUE THREAD

**Issue by Karyum** [WebAhead11/carProject#4]
https://github.com/WebAhead11/carProject/blob/main/src/public/main.js#L53-L67

currently this is not a problem, but it's good to know the danger of this. if in the future the data that you are showing on the page comes from a user (let's say a user made a post on facebook), then whatever the user writes the `innerHtml` will take that data and run it as html, what if the user made a post and in the post he wrote this `<script>alert('Hello')</script>. then whoever is reading the post will get a random alert.

It's generally better to use `textContent`

I had to write this in a hurry if there are any questions at me on the group

**Comment by shadysalem** [comment]
solid point, we'll use textContent next time
